CREATE TABLE "Friendship" (
        "friendshipID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "userID" NUMBER,
        "friendID" NUMBER ,
        "createdTime" TIMESTAMP,
        CONSTRAINT "FK_User_Friend" FOREIGN KEY ("userID") REFERENCES "User"("userID"),
        CONSTRAINT "FK_Friend_User" FOREIGN KEY ("friendID") REFERENCES "User"("userID"),
        CONSTRAINT "UQ_User_Friend" UNIQUE ("userID", "friendID")
);