CREATE TABLE "CourseSchedule" (
    "scheduleID" NUMBER GENERATED BY DEFAULT AS IDENTITY,
    "classID" NUMBER,
    "dayOfWeek" NUMBER,
    "classTime" VARCHAR(20),
    CONSTRAINT "PK_CourseSchedule" PRIMARY KEY ("scheduleID"),
    CONSTRAINT "FK_CourseSchedulet_Course" FOREIGN KEY ("classID") REFERENCES "Course"("classID") ON DELETE CASCADE
);